const dosenList = [
      { nama: "Dr. Ir. Bagus Sumargo, M.Si.", hadir: true },
      { nama: "Dr. Makmuri, M.Si.", hadir: false },
      { nama: "Prof. Dr. Wardani Rahayu, M.Si.", hadir: true },
      { nama: "Dr. Pinta Deniyanti Sampoerno, M.Si.", hadir: false },
      { nama: "Dr. Ellis Salsabila, M.Si.", hadir: true },
      { nama: "Prof. Dr. Suyono, M.Si.", hadir: true },
      { nama: "Drs. Tri Murdiyanto, M.Si.", hadir: false },
      { nama: "Drs. Sudarwanto, M.Si, DEA.", hadir: true },
      { nama: "Drs. Mulyono, M.Kom.", hadir: false },
      { nama: "Dr. Dian Handayani, M.Si.", hadir: true },
      { nama: "Dra. Widyanti Rahayu, M.Si.", hadir: true },
      { nama: "Dr. Lukita Ambarwati, S.Pd., M.Si.", hadir: false },
      { nama: "Ratna Widyati, S.Si., M.Kom.", hadir: true },
      { nama: "Med Irzal, M.Kom.", hadir: false },
      { nama: "Dr. Vera Maya Santi, M.Si.", hadir: true },
      { nama: "Dr. Ria Arafiyah, M.Si.", hadir: false },
      { nama: "Dr. Eti Dwi Wiraningsih, S.Pd., M.Si.", hadir: true },
      { nama: "Dr. Lukman El Hakim, M.Pd.", hadir: false },
      { nama: "Aris Hadiyan Wijaksana, M.Pd.", hadir: true },
      { nama: "Ibnu Hadi, M.Si.", hadir: false },
      { nama: "Dwi Antari Wijayanti, M.Pd.", hadir: true },
      { nama: "Dr. Yudi Mahatma, M.Si.", hadir: false },
      { nama: "Dr. Meiliasari, S.Pd., M.Sc.", hadir: true },
      { nama: "Dr. Puspita Sari, S.Pd., M.Sc.", hadir: false },
      { nama: "Muhammad Eka Suryana, M.Kom", hadir: true },
      { nama: "Debby Agustine, M.Si.", hadir: false },
      { nama: "Dr. Siti Rohmah Rohimah, S.Pd., M.Si.", hadir: true },
      { nama: "Dania Siregar, S.Stat., M.Si.", hadir: false },
      { nama: "Ari Hendarno, S.Pd, M.Kom.", hadir: true },
      { nama: "Dr. Mimi Nur Hajizah, M.Pd. ", hadir: false },
      { nama: "Tian Abdul Aziz, Ph.D.", hadir: true },
      { nama: "Devi Eka Wardani Meganingtyas, S.Pd., M.Si.", hadir: false },
      { nama: "Qorry Meidianingsih, M.Si.", hadir: true },
      { nama: "Leny Dhianti Haeruman, M.Pd.", hadir: false },
      { nama: "Dr. Flavia Aurelia Hidajat, S.Pd., M.Pd.", hadir: true },
      { nama: "Faroh Ladayya, M.Si.", hadir: false },
      { nama: "Dr. Anny Sovia, S.Si., M.Pd.", hadir: true },
      { nama: "Agus Agung Permana, S.Si., M.Pd.", hadir: false },
      { nama: "Nurashri Partasiwi, S.Si., M.Pd.", hadir: true },
      { nama: "Kaola Rachma Adzima, S.Pd., M.Si.", hadir: false },
      { nama: "Nilam Novita Sari, S.Stat., M.Stat.", hadir: true },
      { nama: "Tiara Husnul Khotimah, M.Si.", hadir: false },
      { nama: "Muhammad Rido Wujudi, S.Si., M.Sc.", hadir: true },
      { nama: "Khoiruz Zahra, S.Si., M.Si.", hadir: false },
      { nama: "Eka Rahmi Kahar, S.Si., M.Si.", hadir: true },
      { nama: "Luqman Nuradi Prawadika, S.Si., M.Si.", hadir: false },
      { nama: "Carli Apriansyah Hutagalung, M.Kom", hadir: true },
      { nama: "Endang Yuliani, S.Mat., M.Si", hadir: false },
      { nama: "Ersa Resita, S.Tr.T., M.Tr.Kom", hadir: true },
      { nama: "⁠Linda Devi Fitriana, S.Pd., M.Pd., Ph.D.", hadir: false },
      { nama: "Muhammad Arib Alwansyah, S.Stat., M.Stat.", hadir: true },
      { nama: "Dessy Julita Sari, S.Pd., M.Si.", hadir: false },
      { nama: "Dinar Munggaran Akhmad, S.Kom., M.Kom.", hadir: true },
      { nama: "Ratna Maryam, M.Pd.", hadir: false },
      { nama: "⁠Ndaru Atmi Purnami, S.Si., M.Sc.", hadir: true },
      { nama: "Citra Komang Sari, M.Si", hadir: false },
      { nama: "Ridho Suharis, M.Mat", hadir: true }
    ];